include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - test/**
    - packages/**

linter:
  rules:
    - sort_pub_dependencies
    - sort_constructors_first
    - prefer_relative_imports

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list

  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
    
  metrics-exclude:
    - test/**
    
  rules:
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else