name: chloe
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:  
  adobe_xd: ^2.0.1
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.1.2  
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.6  
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.3
  http: ^0.13.6
  image: ^4.0.17
  provider: ^6.0.5
  sleek_circular_slider : ^2.0.1
  translator: ^0.1.7
  url_launcher: ^6.1.11
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Segoe UI
      fonts:
        - asset: assets/fonts/SegoeUI.ttf
        - asset: assets/fonts/SegoeUI-Bold.ttf
          weight: 700
        - asset: assets/fonts/SegoeUI-Italic.ttf
          style: italic
        - asset: assets/fonts/SegoeUI-BoldItalic.ttf
          weight: 700
          style: italic